Add a function that will allow downloading the correct version of env-var-docs.json
civiform/cloud-deploy-infra pull request #154
Opened 2023-04-27 18:48 UTC by jessbumblebee

This change ads a function that can get the commit sha for a specific version.
In the future, after #132 is submitted, this should be used in config_loader to download the correct version of 
en-var-docs.json. The version that is downloaded in #132 hardcodes a commit sha, which will break in the future
when en-var-docs has changed.

A second similar change will be needed to also download the correct version of the python package in the run script, which installs the python dependencies.

2023-05-04 23:55 UTC, rockycodes requested changes

2023-05-04 23:55 UTC, rockycodes commented on cloud/shared/bin/lib/config_loader.py
> +                newtag = response.json()["tag_name"]
question (non-blocking): why assign this to newtag?

2023-05-04 23:55 UTC, rockycodes commented on cloud/shared/bin/lib/config_loader_test.py
> +        # mock out getting te version number that matches "latest"
```suggestion
        # mock out getting the version number that matches "latest"
```

2023-05-04 23:55 UTC, rockycodes commented on cloud/shared/bin/lib/config_loader_test.py
> +        #mock_requests.assert_called_with("https://api.github.com/repos/civiform/civiform/git/refs/tags/V1.0.0")
suggestion (blocking): delete or comment back in.

2023-05-04 23:55 UTC, rockycodes commented on cloud/shared/bin/lib/config_loader_test.py
> +
suggestion (non-blocking): add a test case for passing in a tag other than "latest" (could use "v1.23.0" from your mock)

2023-05-05 00:00 UTC, bion approved these changes
Overall looks good! Just some cleanup stuff. Approving so you can merge as desired without waiting for another review.

2023-05-05 00:14 UTC, rockycodes approved these changes

2023-05-19 23:32 UTC, rockycodes commented on cloud/shared/bin/env-var-docs-python-dependencies.txt
> +requests
@bion I wasn't sure how to do this.

2023-05-19 23:32 UTC, rockycodes commented on cloud/shared/bin/lib/config_loader.py
> +        if tag.strip() == 'latest':
done

2023-05-19 23:32 UTC, rockycodes commented on cloud/shared/bin/lib/config_loader.py
> +            url = f"https://api.github.com/repos/civiform/civiform/releases/latest"
I opted not to extract these url strings to constants since they are not reused.

2023-05-19 23:32 UTC, rockycodes commented on cloud/shared/bin/lib/config_loader.py
> +                newtag = response.json()["tag_name"]
done

2023-05-22 20:17 UTC, rockycodes commented on cloud/shared/bin/env-var-docs-python-dependencies.txt
> +requests
done!

2023-05-22 20:24 UTC, bion approved these changes

2023-05-22 21:29 UTC, merged