Rockycodes/cleanup autogenerated vars
civiform/cloud-deploy-infra pull request #268
Opened 2023-10-30 21:12 UTC by rockycodes

2023-11-01 23:18 UTC, bion requested changes
Thank you!!! This has been a long time coming, great to see it finally happen.

It looks like there are a few vars that could also be removed from here? https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/aws/templates/aws_oidc/variable_definitions.json#L44

2023-11-02 15:16 UTC, rockycodes commented
> Thank you!!! This has been a long time coming, great to see it finally happen.
> 
> It looks like there are a few vars that could also be removed from here? https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/aws/templates/aws_oidc/variable_definitions.json#L44

@bion what vars in particular? I'm removing the line you linked to [here](https://github.com/civiform/cloud-deploy-infra/pull/268/files#diff-d5f0de2a0a2dad8f4fe13e04fa34e7cf2389688766f0d656873bfc4c8c25f44fL44)

2023-11-02 19:54 UTC, rockycodes commented
> Looks good! I wonder if some of those marked as "used elsewhere" could be refactored later, e.g. AWS_SES_SENDER is really SENDER_EMAIL_ADDRESS, can we just use AWS_SES_SENDER everywhere instead of SENDER_EMAIL_ADDRESS? But definitely not needed for this one.

Good idea, I can make an issue to follow up with that.

2023-11-02 20:02 UTC, bion approved these changes

2023-11-02 20:05 UTC, merged